/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 37
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 27
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_single_line_key = 1,
  sym_key_continuation = 2,
  sym_assignment = 3,
  aux_sym_single_line_value_token1 = 4,
  aux_sym_multiline_value_token1 = 5,
  anon_sym_SLASH_EQ = 6,
  aux_sym_comment_token1 = 7,
  sym_newline = 8,
  sym_indent = 9,
  sym_dedent = 10,
  sym_document = 11,
  sym__item = 12,
  sym_entry = 13,
  sym_multiline_key = 14,
  sym__value = 15,
  sym_single_line_value = 16,
  sym_nested_content = 17,
  sym_content_line = 18,
  sym_multiline_value = 19,
  sym_comment = 20,
  sym_multiline_comment_content = 21,
  sym_comment_content_line = 22,
  aux_sym_document_repeat1 = 23,
  aux_sym_nested_content_repeat1 = 24,
  aux_sym_multiline_value_repeat1 = 25,
  aux_sym_multiline_comment_content_repeat1 = 26,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_single_line_key] = "single_line_key",
  [sym_key_continuation] = "key_continuation",
  [sym_assignment] = "assignment",
  [aux_sym_single_line_value_token1] = "single_line_value_token1",
  [aux_sym_multiline_value_token1] = "value_line",
  [anon_sym_SLASH_EQ] = "comment_marker",
  [aux_sym_comment_token1] = "comment_text",
  [sym_newline] = "newline",
  [sym_indent] = "indent",
  [sym_dedent] = "dedent",
  [sym_document] = "document",
  [sym__item] = "_item",
  [sym_entry] = "entry",
  [sym_multiline_key] = "multiline_key",
  [sym__value] = "_value",
  [sym_single_line_value] = "single_line_value",
  [sym_nested_content] = "nested_content",
  [sym_content_line] = "content_line",
  [sym_multiline_value] = "multiline_value",
  [sym_comment] = "comment",
  [sym_multiline_comment_content] = "multiline_comment_content",
  [sym_comment_content_line] = "comment_content_line",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_nested_content_repeat1] = "nested_content_repeat1",
  [aux_sym_multiline_value_repeat1] = "multiline_value_repeat1",
  [aux_sym_multiline_comment_content_repeat1] = "multiline_comment_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_single_line_key] = sym_single_line_key,
  [sym_key_continuation] = sym_key_continuation,
  [sym_assignment] = sym_assignment,
  [aux_sym_single_line_value_token1] = aux_sym_single_line_value_token1,
  [aux_sym_multiline_value_token1] = aux_sym_multiline_value_token1,
  [anon_sym_SLASH_EQ] = anon_sym_SLASH_EQ,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_newline] = sym_newline,
  [sym_indent] = sym_indent,
  [sym_dedent] = sym_dedent,
  [sym_document] = sym_document,
  [sym__item] = sym__item,
  [sym_entry] = sym_entry,
  [sym_multiline_key] = sym_multiline_key,
  [sym__value] = sym__value,
  [sym_single_line_value] = sym_single_line_value,
  [sym_nested_content] = sym_nested_content,
  [sym_content_line] = sym_content_line,
  [sym_multiline_value] = sym_multiline_value,
  [sym_comment] = sym_comment,
  [sym_multiline_comment_content] = sym_multiline_comment_content,
  [sym_comment_content_line] = sym_comment_content_line,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_nested_content_repeat1] = aux_sym_nested_content_repeat1,
  [aux_sym_multiline_value_repeat1] = aux_sym_multiline_value_repeat1,
  [aux_sym_multiline_comment_content_repeat1] = aux_sym_multiline_comment_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_single_line_key] = {
    .visible = true,
    .named = true,
  },
  [sym_key_continuation] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_single_line_value_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multiline_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_EQ] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_indent] = {
    .visible = true,
    .named = true,
  },
  [sym_dedent] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_key] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_single_line_value] = {
    .visible = true,
    .named = true,
  },
  [sym_nested_content] = {
    .visible = true,
    .named = true,
  },
  [sym_content_line] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_value] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_comment_content] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_content_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_nested_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multiline_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multiline_comment_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = aux_sym_comment_token1,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (lookahead == '/') ADVANCE(1);
      if (lookahead == '=') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(5);
      END_STATE();
    case 1:
      if (lookahead == '=') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/' &&
          lookahead != '=') ADVANCE(15);
      END_STATE();
    case 3:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(7);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_single_line_key);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(5);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_key_continuation);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(7);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_key_continuation);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_assignment);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_single_line_value_token1);
      if (lookahead == '/') ADVANCE(10);
      if (lookahead == '=') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(10);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_single_line_value_token1);
      if (lookahead == '=') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_single_line_value_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead == '/' ||
          lookahead == '=') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(10);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_single_line_value_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_single_line_value_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_multiline_value_token1);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_multiline_value_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_SLASH_EQ);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(18);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 11, .external_lex_state = 3},
  [5] = {.lex_state = 12, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 12, .external_lex_state = 3},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 12, .external_lex_state = 3},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 12, .external_lex_state = 4},
  [18] = {.lex_state = 12, .external_lex_state = 4},
  [19] = {.lex_state = 12},
  [20] = {.lex_state = 2, .external_lex_state = 4},
  [21] = {.lex_state = 12, .external_lex_state = 3},
  [22] = {.lex_state = 2, .external_lex_state = 4},
  [23] = {.lex_state = 12},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 2, .external_lex_state = 4},
  [26] = {.lex_state = 12, .external_lex_state = 4},
  [27] = {.lex_state = 12},
  [28] = {.lex_state = 0, .external_lex_state = 5},
  [29] = {.lex_state = 17},
  [30] = {.lex_state = 0, .external_lex_state = 2},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0, .external_lex_state = 2},
  [34] = {.lex_state = 0, .external_lex_state = 5},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_single_line_key] = ACTIONS(1),
    [sym_assignment] = ACTIONS(1),
    [anon_sym_SLASH_EQ] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [sym_indent] = ACTIONS(1),
    [sym_dedent] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(32),
    [sym__item] = STATE(2),
    [sym_entry] = STATE(2),
    [sym_multiline_key] = STATE(31),
    [sym_comment] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_single_line_key] = ACTIONS(5),
    [sym_assignment] = ACTIONS(7),
    [anon_sym_SLASH_EQ] = ACTIONS(9),
    [sym_newline] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(5), 1,
      sym_single_line_key,
    ACTIONS(7), 1,
      sym_assignment,
    ACTIONS(9), 1,
      anon_sym_SLASH_EQ,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      sym_newline,
    STATE(31), 1,
      sym_multiline_key,
    STATE(3), 4,
      sym__item,
      sym_entry,
      sym_comment,
      aux_sym_document_repeat1,
  [25] = 7,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      sym_single_line_key,
    ACTIONS(22), 1,
      sym_assignment,
    ACTIONS(25), 1,
      anon_sym_SLASH_EQ,
    ACTIONS(28), 1,
      sym_newline,
    STATE(31), 1,
      sym_multiline_key,
    STATE(3), 4,
      sym__item,
      sym_entry,
      sym_comment,
      aux_sym_document_repeat1,
  [50] = 6,
    ACTIONS(31), 1,
      aux_sym_single_line_value_token1,
    ACTIONS(33), 1,
      aux_sym_multiline_value_token1,
    ACTIONS(35), 1,
      sym_newline,
    ACTIONS(37), 1,
      sym_dedent,
    STATE(20), 1,
      aux_sym_multiline_value_repeat1,
    STATE(12), 2,
      sym_content_line,
      aux_sym_nested_content_repeat1,
  [70] = 3,
    ACTIONS(39), 1,
      aux_sym_single_line_value_token1,
    ACTIONS(41), 1,
      sym_newline,
    STATE(9), 4,
      sym__value,
      sym_single_line_value,
      sym_nested_content,
      sym_multiline_value,
  [83] = 3,
    ACTIONS(45), 1,
      sym_newline,
    STATE(11), 1,
      sym_multiline_comment_content,
    ACTIONS(43), 4,
      ts_builtin_sym_end,
      sym_single_line_key,
      sym_assignment,
      anon_sym_SLASH_EQ,
  [96] = 1,
    ACTIONS(48), 5,
      sym_newline,
      ts_builtin_sym_end,
      sym_single_line_key,
      sym_assignment,
      anon_sym_SLASH_EQ,
  [104] = 1,
    ACTIONS(50), 5,
      sym_newline,
      ts_builtin_sym_end,
      sym_single_line_key,
      sym_assignment,
      anon_sym_SLASH_EQ,
  [112] = 1,
    ACTIONS(52), 5,
      sym_newline,
      ts_builtin_sym_end,
      sym_single_line_key,
      sym_assignment,
      anon_sym_SLASH_EQ,
  [120] = 1,
    ACTIONS(54), 5,
      sym_newline,
      ts_builtin_sym_end,
      sym_single_line_key,
      sym_assignment,
      anon_sym_SLASH_EQ,
  [128] = 1,
    ACTIONS(56), 5,
      sym_newline,
      ts_builtin_sym_end,
      sym_single_line_key,
      sym_assignment,
      anon_sym_SLASH_EQ,
  [136] = 4,
    ACTIONS(58), 1,
      aux_sym_single_line_value_token1,
    ACTIONS(60), 1,
      sym_newline,
    ACTIONS(62), 1,
      sym_dedent,
    STATE(14), 2,
      sym_content_line,
      aux_sym_nested_content_repeat1,
  [150] = 1,
    ACTIONS(64), 5,
      sym_newline,
      ts_builtin_sym_end,
      sym_single_line_key,
      sym_assignment,
      anon_sym_SLASH_EQ,
  [158] = 4,
    ACTIONS(66), 1,
      aux_sym_single_line_value_token1,
    ACTIONS(69), 1,
      sym_newline,
    ACTIONS(72), 1,
      sym_dedent,
    STATE(14), 2,
      sym_content_line,
      aux_sym_nested_content_repeat1,
  [172] = 1,
    ACTIONS(74), 5,
      sym_newline,
      ts_builtin_sym_end,
      sym_single_line_key,
      sym_assignment,
      anon_sym_SLASH_EQ,
  [180] = 1,
    ACTIONS(76), 5,
      sym_newline,
      ts_builtin_sym_end,
      sym_single_line_key,
      sym_assignment,
      anon_sym_SLASH_EQ,
  [188] = 3,
    ACTIONS(78), 1,
      aux_sym_single_line_value_token1,
    ACTIONS(80), 1,
      sym_dedent,
    STATE(18), 2,
      sym_comment_content_line,
      aux_sym_multiline_comment_content_repeat1,
  [199] = 3,
    ACTIONS(82), 1,
      aux_sym_single_line_value_token1,
    ACTIONS(85), 1,
      sym_dedent,
    STATE(18), 2,
      sym_comment_content_line,
      aux_sym_multiline_comment_content_repeat1,
  [210] = 2,
    ACTIONS(78), 1,
      aux_sym_single_line_value_token1,
    STATE(17), 2,
      sym_comment_content_line,
      aux_sym_multiline_comment_content_repeat1,
  [218] = 3,
    ACTIONS(87), 1,
      aux_sym_multiline_value_token1,
    ACTIONS(89), 1,
      sym_dedent,
    STATE(22), 1,
      aux_sym_multiline_value_repeat1,
  [228] = 1,
    ACTIONS(91), 3,
      sym_newline,
      sym_dedent,
      aux_sym_single_line_value_token1,
  [234] = 3,
    ACTIONS(93), 1,
      aux_sym_multiline_value_token1,
    ACTIONS(96), 1,
      sym_dedent,
    STATE(22), 1,
      aux_sym_multiline_value_repeat1,
  [244] = 2,
    ACTIONS(39), 1,
      aux_sym_single_line_value_token1,
    STATE(8), 1,
      sym_single_line_value,
  [251] = 2,
    ACTIONS(98), 1,
      sym_assignment,
    ACTIONS(100), 1,
      sym_newline,
  [258] = 1,
    ACTIONS(96), 2,
      sym_dedent,
      aux_sym_multiline_value_token1,
  [263] = 1,
    ACTIONS(102), 2,
      sym_dedent,
      aux_sym_single_line_value_token1,
  [268] = 2,
    ACTIONS(39), 1,
      aux_sym_single_line_value_token1,
    STATE(9), 1,
      sym_single_line_value,
  [275] = 1,
    ACTIONS(104), 1,
      sym_indent,
  [279] = 1,
    ACTIONS(106), 1,
      aux_sym_comment_token1,
  [283] = 1,
    ACTIONS(108), 1,
      sym_newline,
  [287] = 1,
    ACTIONS(110), 1,
      sym_assignment,
  [291] = 1,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
  [295] = 1,
    ACTIONS(114), 1,
      sym_newline,
  [299] = 1,
    ACTIONS(116), 1,
      sym_indent,
  [303] = 1,
    ACTIONS(118), 1,
      sym_assignment,
  [307] = 1,
    ACTIONS(120), 1,
      sym_key_continuation,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 25,
  [SMALL_STATE(4)] = 50,
  [SMALL_STATE(5)] = 70,
  [SMALL_STATE(6)] = 83,
  [SMALL_STATE(7)] = 96,
  [SMALL_STATE(8)] = 104,
  [SMALL_STATE(9)] = 112,
  [SMALL_STATE(10)] = 120,
  [SMALL_STATE(11)] = 128,
  [SMALL_STATE(12)] = 136,
  [SMALL_STATE(13)] = 150,
  [SMALL_STATE(14)] = 158,
  [SMALL_STATE(15)] = 172,
  [SMALL_STATE(16)] = 180,
  [SMALL_STATE(17)] = 188,
  [SMALL_STATE(18)] = 199,
  [SMALL_STATE(19)] = 210,
  [SMALL_STATE(20)] = 218,
  [SMALL_STATE(21)] = 228,
  [SMALL_STATE(22)] = 234,
  [SMALL_STATE(23)] = 244,
  [SMALL_STATE(24)] = 251,
  [SMALL_STATE(25)] = 258,
  [SMALL_STATE(26)] = 263,
  [SMALL_STATE(27)] = 268,
  [SMALL_STATE(28)] = 275,
  [SMALL_STATE(29)] = 279,
  [SMALL_STATE(30)] = 283,
  [SMALL_STATE(31)] = 287,
  [SMALL_STATE(32)] = 291,
  [SMALL_STATE(33)] = 295,
  [SMALL_STATE(34)] = 299,
  [SMALL_STATE(35)] = 303,
  [SMALL_STATE(36)] = 307,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0), SHIFT(28),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_line_value, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 3, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_content, 3, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 2, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_content, 4, 0, 0),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nested_content_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nested_content_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_nested_content_repeat1, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_value, 4, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_comment_content, 4, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_multiline_comment_content_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multiline_comment_content_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content_line, 1, 0, 0),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_multiline_value_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multiline_value_repeat1, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_content_line, 2, 0, 1),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [112] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_key, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_newline = 0,
  ts_external_token_indent = 1,
  ts_external_token_dedent = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_newline] = sym_newline,
  [ts_external_token_indent] = sym_indent,
  [ts_external_token_dedent] = sym_dedent,
};

static const bool ts_external_scanner_states[6][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_newline] = true,
    [ts_external_token_indent] = true,
    [ts_external_token_dedent] = true,
  },
  [2] = {
    [ts_external_token_newline] = true,
  },
  [3] = {
    [ts_external_token_newline] = true,
    [ts_external_token_dedent] = true,
  },
  [4] = {
    [ts_external_token_dedent] = true,
  },
  [5] = {
    [ts_external_token_indent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_ccl_external_scanner_create(void);
void tree_sitter_ccl_external_scanner_destroy(void *);
bool tree_sitter_ccl_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_ccl_external_scanner_serialize(void *, char *);
void tree_sitter_ccl_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ccl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_ccl_external_scanner_create,
      tree_sitter_ccl_external_scanner_destroy,
      tree_sitter_ccl_external_scanner_scan,
      tree_sitter_ccl_external_scanner_serialize,
      tree_sitter_ccl_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "ccl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
