/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 37
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_single_line_key = 1,
  sym_key_continuation = 2,
  sym_assignment = 3,
  sym_single_line_value = 4,
  aux_sym_content_line_token1 = 5,
  aux_sym_multiline_value_block_token1 = 6,
  anon_sym_SLASH_EQ = 7,
  aux_sym_comment_token1 = 8,
  sym_newline = 9,
  sym_indent = 10,
  sym_dedent = 11,
  sym_document = 12,
  sym__item = 13,
  sym_entry = 14,
  sym_key = 15,
  sym_multiline_key = 16,
  sym__value = 17,
  sym_nested_content_block = 18,
  sym_content_line = 19,
  sym_multiline_value_block = 20,
  sym_comment = 21,
  sym_multiline_comment_content = 22,
  sym_comment_content_line = 23,
  aux_sym_document_repeat1 = 24,
  aux_sym_nested_content_block_repeat1 = 25,
  aux_sym_multiline_value_block_repeat1 = 26,
  aux_sym_multiline_comment_content_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_single_line_key] = "single_line_key",
  [sym_key_continuation] = "key_continuation",
  [sym_assignment] = "assignment",
  [sym_single_line_value] = "single_line_value",
  [aux_sym_content_line_token1] = "content_line_token1",
  [aux_sym_multiline_value_block_token1] = "value_line",
  [anon_sym_SLASH_EQ] = "comment_marker",
  [aux_sym_comment_token1] = "comment_text",
  [sym_newline] = "newline",
  [sym_indent] = "indent",
  [sym_dedent] = "dedent",
  [sym_document] = "document",
  [sym__item] = "_item",
  [sym_entry] = "entry",
  [sym_key] = "key",
  [sym_multiline_key] = "multiline_key",
  [sym__value] = "_value",
  [sym_nested_content_block] = "nested_content_block",
  [sym_content_line] = "content_line",
  [sym_multiline_value_block] = "multiline_value_block",
  [sym_comment] = "comment",
  [sym_multiline_comment_content] = "multiline_comment_content",
  [sym_comment_content_line] = "comment_content_line",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_nested_content_block_repeat1] = "nested_content_block_repeat1",
  [aux_sym_multiline_value_block_repeat1] = "multiline_value_block_repeat1",
  [aux_sym_multiline_comment_content_repeat1] = "multiline_comment_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_single_line_key] = sym_single_line_key,
  [sym_key_continuation] = sym_key_continuation,
  [sym_assignment] = sym_assignment,
  [sym_single_line_value] = sym_single_line_value,
  [aux_sym_content_line_token1] = aux_sym_content_line_token1,
  [aux_sym_multiline_value_block_token1] = aux_sym_multiline_value_block_token1,
  [anon_sym_SLASH_EQ] = anon_sym_SLASH_EQ,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_newline] = sym_newline,
  [sym_indent] = sym_indent,
  [sym_dedent] = sym_dedent,
  [sym_document] = sym_document,
  [sym__item] = sym__item,
  [sym_entry] = sym_entry,
  [sym_key] = sym_key,
  [sym_multiline_key] = sym_multiline_key,
  [sym__value] = sym__value,
  [sym_nested_content_block] = sym_nested_content_block,
  [sym_content_line] = sym_content_line,
  [sym_multiline_value_block] = sym_multiline_value_block,
  [sym_comment] = sym_comment,
  [sym_multiline_comment_content] = sym_multiline_comment_content,
  [sym_comment_content_line] = sym_comment_content_line,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_nested_content_block_repeat1] = aux_sym_nested_content_block_repeat1,
  [aux_sym_multiline_value_block_repeat1] = aux_sym_multiline_value_block_repeat1,
  [aux_sym_multiline_comment_content_repeat1] = aux_sym_multiline_comment_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_single_line_key] = {
    .visible = true,
    .named = true,
  },
  [sym_key_continuation] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_single_line_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_content_line_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multiline_value_block_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_EQ] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_indent] = {
    .visible = true,
    .named = true,
  },
  [sym_dedent] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_key] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_nested_content_block] = {
    .visible = true,
    .named = true,
  },
  [sym_content_line] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_value_block] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_comment_content] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_content_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_nested_content_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multiline_value_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multiline_comment_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = aux_sym_comment_token1,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '/') ADVANCE(13);
      if (lookahead == '=') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(14);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(12);
      END_STATE();
    case 1:
      if (lookahead == '=') ADVANCE(22);
      END_STATE();
    case 2:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '/' &&
          lookahead != '=') ADVANCE(21);
      END_STATE();
    case 3:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(8);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      if (lookahead == '/') ADVANCE(1);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(6);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_single_line_key);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_key_continuation);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(8);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_key_continuation);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_assignment);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_assignment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(14);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_single_line_value);
      if (lookahead == '/') ADVANCE(13);
      if (lookahead == '=') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(14);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(12);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_single_line_value);
      if (lookahead == '=') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_single_line_value);
      if (lookahead == '=') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_single_line_value);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_content_line_token1);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '=') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_content_line_token1);
      if (lookahead == '=') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_content_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead == '/' ||
          lookahead == '=') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_content_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_content_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_multiline_value_block_token1);
      if (lookahead == '/') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_multiline_value_block_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SLASH_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SLASH_EQ);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(14);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(25);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 4, .external_lex_state = 2},
  [2] = {.lex_state = 4, .external_lex_state = 2},
  [3] = {.lex_state = 4, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 17, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 4, .external_lex_state = 2},
  [8] = {.lex_state = 4, .external_lex_state = 2},
  [9] = {.lex_state = 4, .external_lex_state = 2},
  [10] = {.lex_state = 4, .external_lex_state = 2},
  [11] = {.lex_state = 4, .external_lex_state = 2},
  [12] = {.lex_state = 4, .external_lex_state = 2},
  [13] = {.lex_state = 4, .external_lex_state = 2},
  [14] = {.lex_state = 4, .external_lex_state = 2},
  [15] = {.lex_state = 18, .external_lex_state = 3},
  [16] = {.lex_state = 18, .external_lex_state = 3},
  [17] = {.lex_state = 4, .external_lex_state = 2},
  [18] = {.lex_state = 18, .external_lex_state = 4},
  [19] = {.lex_state = 18, .external_lex_state = 4},
  [20] = {.lex_state = 0, .external_lex_state = 5},
  [21] = {.lex_state = 18},
  [22] = {.lex_state = 18, .external_lex_state = 3},
  [23] = {.lex_state = 2, .external_lex_state = 4},
  [24] = {.lex_state = 2, .external_lex_state = 4},
  [25] = {.lex_state = 4, .external_lex_state = 2},
  [26] = {.lex_state = 18, .external_lex_state = 4},
  [27] = {.lex_state = 2, .external_lex_state = 4},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 24},
  [32] = {.lex_state = 0, .external_lex_state = 5},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 0, .external_lex_state = 2},
  [36] = {.lex_state = 0, .external_lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_single_line_key] = ACTIONS(1),
    [sym_assignment] = ACTIONS(1),
    [sym_single_line_value] = ACTIONS(1),
    [anon_sym_SLASH_EQ] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [sym_indent] = ACTIONS(1),
    [sym_dedent] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(28),
    [sym__item] = STATE(2),
    [sym_entry] = STATE(2),
    [sym_key] = STATE(29),
    [sym_multiline_key] = STATE(30),
    [sym_comment] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_single_line_key] = ACTIONS(5),
    [sym_assignment] = ACTIONS(7),
    [anon_sym_SLASH_EQ] = ACTIONS(9),
    [sym_newline] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(5), 1,
      sym_single_line_key,
    ACTIONS(7), 1,
      sym_assignment,
    ACTIONS(9), 1,
      anon_sym_SLASH_EQ,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      sym_newline,
    STATE(29), 1,
      sym_key,
    STATE(30), 1,
      sym_multiline_key,
    STATE(3), 4,
      sym__item,
      sym_entry,
      sym_comment,
      aux_sym_document_repeat1,
  [28] = 8,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      sym_single_line_key,
    ACTIONS(22), 1,
      sym_assignment,
    ACTIONS(25), 1,
      anon_sym_SLASH_EQ,
    ACTIONS(28), 1,
      sym_newline,
    STATE(29), 1,
      sym_key,
    STATE(30), 1,
      sym_multiline_key,
    STATE(3), 4,
      sym__item,
      sym_entry,
      sym_comment,
      aux_sym_document_repeat1,
  [56] = 5,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      sym_single_line_value,
    ACTIONS(37), 1,
      sym_newline,
    STATE(11), 1,
      sym__value,
    ACTIONS(33), 3,
      sym_single_line_key,
      sym_assignment,
      anon_sym_SLASH_EQ,
  [74] = 6,
    ACTIONS(40), 1,
      aux_sym_content_line_token1,
    ACTIONS(42), 1,
      aux_sym_multiline_value_block_token1,
    ACTIONS(44), 1,
      sym_newline,
    ACTIONS(46), 1,
      sym_dedent,
    STATE(23), 1,
      aux_sym_multiline_value_block_repeat1,
    STATE(15), 2,
      sym_content_line,
      aux_sym_nested_content_block_repeat1,
  [94] = 3,
    ACTIONS(52), 1,
      sym_single_line_value,
    ACTIONS(48), 2,
      sym_newline,
      ts_builtin_sym_end,
    ACTIONS(50), 3,
      sym_single_line_key,
      sym_assignment,
      anon_sym_SLASH_EQ,
  [107] = 3,
    ACTIONS(56), 1,
      sym_newline,
    STATE(8), 1,
      sym_multiline_comment_content,
    ACTIONS(54), 4,
      ts_builtin_sym_end,
      sym_single_line_key,
      sym_assignment,
      anon_sym_SLASH_EQ,
  [120] = 1,
    ACTIONS(59), 5,
      sym_newline,
      ts_builtin_sym_end,
      sym_single_line_key,
      sym_assignment,
      anon_sym_SLASH_EQ,
  [128] = 1,
    ACTIONS(61), 5,
      sym_newline,
      ts_builtin_sym_end,
      sym_single_line_key,
      sym_assignment,
      anon_sym_SLASH_EQ,
  [136] = 1,
    ACTIONS(31), 5,
      sym_newline,
      ts_builtin_sym_end,
      sym_single_line_key,
      sym_assignment,
      anon_sym_SLASH_EQ,
  [144] = 1,
    ACTIONS(63), 5,
      sym_newline,
      ts_builtin_sym_end,
      sym_single_line_key,
      sym_assignment,
      anon_sym_SLASH_EQ,
  [152] = 1,
    ACTIONS(65), 5,
      sym_newline,
      ts_builtin_sym_end,
      sym_single_line_key,
      sym_assignment,
      anon_sym_SLASH_EQ,
  [160] = 1,
    ACTIONS(67), 5,
      sym_newline,
      ts_builtin_sym_end,
      sym_single_line_key,
      sym_assignment,
      anon_sym_SLASH_EQ,
  [168] = 1,
    ACTIONS(69), 5,
      sym_newline,
      ts_builtin_sym_end,
      sym_single_line_key,
      sym_assignment,
      anon_sym_SLASH_EQ,
  [176] = 4,
    ACTIONS(71), 1,
      aux_sym_content_line_token1,
    ACTIONS(73), 1,
      sym_newline,
    ACTIONS(75), 1,
      sym_dedent,
    STATE(16), 2,
      sym_content_line,
      aux_sym_nested_content_block_repeat1,
  [190] = 4,
    ACTIONS(77), 1,
      aux_sym_content_line_token1,
    ACTIONS(80), 1,
      sym_newline,
    ACTIONS(83), 1,
      sym_dedent,
    STATE(16), 2,
      sym_content_line,
      aux_sym_nested_content_block_repeat1,
  [204] = 1,
    ACTIONS(85), 5,
      sym_newline,
      ts_builtin_sym_end,
      sym_single_line_key,
      sym_assignment,
      anon_sym_SLASH_EQ,
  [212] = 3,
    ACTIONS(87), 1,
      aux_sym_content_line_token1,
    ACTIONS(90), 1,
      sym_dedent,
    STATE(18), 2,
      sym_comment_content_line,
      aux_sym_multiline_comment_content_repeat1,
  [223] = 3,
    ACTIONS(92), 1,
      aux_sym_content_line_token1,
    ACTIONS(94), 1,
      sym_dedent,
    STATE(18), 2,
      sym_comment_content_line,
      aux_sym_multiline_comment_content_repeat1,
  [234] = 2,
    ACTIONS(96), 1,
      sym_indent,
    STATE(9), 2,
      sym_nested_content_block,
      sym_multiline_value_block,
  [242] = 2,
    ACTIONS(92), 1,
      aux_sym_content_line_token1,
    STATE(19), 2,
      sym_comment_content_line,
      aux_sym_multiline_comment_content_repeat1,
  [250] = 1,
    ACTIONS(98), 3,
      sym_newline,
      sym_dedent,
      aux_sym_content_line_token1,
  [256] = 3,
    ACTIONS(100), 1,
      aux_sym_multiline_value_block_token1,
    ACTIONS(102), 1,
      sym_dedent,
    STATE(24), 1,
      aux_sym_multiline_value_block_repeat1,
  [266] = 3,
    ACTIONS(104), 1,
      aux_sym_multiline_value_block_token1,
    ACTIONS(107), 1,
      sym_dedent,
    STATE(24), 1,
      aux_sym_multiline_value_block_repeat1,
  [276] = 2,
    ACTIONS(109), 1,
      sym_assignment,
    ACTIONS(111), 1,
      sym_newline,
  [283] = 1,
    ACTIONS(113), 2,
      sym_dedent,
      aux_sym_content_line_token1,
  [288] = 1,
    ACTIONS(107), 2,
      sym_dedent,
      aux_sym_multiline_value_block_token1,
  [293] = 1,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
  [297] = 1,
    ACTIONS(117), 1,
      sym_assignment,
  [301] = 1,
    ACTIONS(109), 1,
      sym_assignment,
  [305] = 1,
    ACTIONS(119), 1,
      aux_sym_comment_token1,
  [309] = 1,
    ACTIONS(121), 1,
      sym_indent,
  [313] = 1,
    ACTIONS(123), 1,
      sym_assignment,
  [317] = 1,
    ACTIONS(125), 1,
      sym_key_continuation,
  [321] = 1,
    ACTIONS(127), 1,
      sym_newline,
  [325] = 1,
    ACTIONS(129), 1,
      sym_newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 28,
  [SMALL_STATE(4)] = 56,
  [SMALL_STATE(5)] = 74,
  [SMALL_STATE(6)] = 94,
  [SMALL_STATE(7)] = 107,
  [SMALL_STATE(8)] = 120,
  [SMALL_STATE(9)] = 128,
  [SMALL_STATE(10)] = 136,
  [SMALL_STATE(11)] = 144,
  [SMALL_STATE(12)] = 152,
  [SMALL_STATE(13)] = 160,
  [SMALL_STATE(14)] = 168,
  [SMALL_STATE(15)] = 176,
  [SMALL_STATE(16)] = 190,
  [SMALL_STATE(17)] = 204,
  [SMALL_STATE(18)] = 212,
  [SMALL_STATE(19)] = 223,
  [SMALL_STATE(20)] = 234,
  [SMALL_STATE(21)] = 242,
  [SMALL_STATE(22)] = 250,
  [SMALL_STATE(23)] = 256,
  [SMALL_STATE(24)] = 266,
  [SMALL_STATE(25)] = 276,
  [SMALL_STATE(26)] = 283,
  [SMALL_STATE(27)] = 288,
  [SMALL_STATE(28)] = 293,
  [SMALL_STATE(29)] = 297,
  [SMALL_STATE(30)] = 301,
  [SMALL_STATE(31)] = 305,
  [SMALL_STATE(32)] = 309,
  [SMALL_STATE(33)] = 313,
  [SMALL_STATE(34)] = 317,
  [SMALL_STATE(35)] = 321,
  [SMALL_STATE(36)] = 325,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entry, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_entry, 2, 0, 0), SHIFT(20),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entry, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0), SHIFT(32),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 2, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_value_block, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_content_block, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_comment_content, 4, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nested_content_block_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nested_content_block_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_nested_content_block_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_content_block, 3, 0, 0),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_multiline_comment_content_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multiline_comment_content_repeat1, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content_line, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_multiline_value_block_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multiline_value_block_repeat1, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_content_line, 2, 0, 1),
  [115] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_key, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_newline = 0,
  ts_external_token_indent = 1,
  ts_external_token_dedent = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_newline] = sym_newline,
  [ts_external_token_indent] = sym_indent,
  [ts_external_token_dedent] = sym_dedent,
};

static const bool ts_external_scanner_states[6][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_newline] = true,
    [ts_external_token_indent] = true,
    [ts_external_token_dedent] = true,
  },
  [2] = {
    [ts_external_token_newline] = true,
  },
  [3] = {
    [ts_external_token_newline] = true,
    [ts_external_token_dedent] = true,
  },
  [4] = {
    [ts_external_token_dedent] = true,
  },
  [5] = {
    [ts_external_token_indent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_ccl_external_scanner_create(void);
void tree_sitter_ccl_external_scanner_destroy(void *);
bool tree_sitter_ccl_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_ccl_external_scanner_serialize(void *, char *);
void tree_sitter_ccl_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ccl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_ccl_external_scanner_create,
      tree_sitter_ccl_external_scanner_destroy,
      tree_sitter_ccl_external_scanner_scan,
      tree_sitter_ccl_external_scanner_serialize,
      tree_sitter_ccl_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "ccl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
