version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      # day: "monday"
      time: "05:00"
      timezone: "America/Los_Angeles"

    # Open PR limit to prevent noise
    open-pull-requests-limit: 10

    # Rebase strategy for clean history
    rebase-strategy: "auto"

    # Versioning strategy
    versioning-strategy: "increase"

    # Ignore patch updates globally (matching renovate config)
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

    # Package groups matching Renovate configuration
    groups:
      oclif:
        patterns:
          - "oclif"
          - "oclif*"
          - "@oclif/*"
        update-types:
          - "minor"

      fluid-framework:
        patterns:
          - "@fluidframework/*"
          - "fluid-framework"
        update-types:
          - "minor"

      typedoc:
        patterns:
          - "typedoc"
          - "typedoc*"
        update-types:
          - "minor"

      typescript:
        patterns:
          - "typescript"
        update-types:
          - "minor"

      svelte:
        patterns:
          - "svelte"
          - "svelte-kit"
        update-types:
          - "minor"

      # All other dependencies (not in above groups)
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "oclif"
          - "oclif*"
          - "@oclif/*"
          - "@fluidframework/*"
          - "fluid-framework"
          - "typedoc*"
          - "typescript"

          # Exclude Astro and Starlight packages from automated updates.
          # These packages are tightly coupled to project-specific configurations and may introduce breaking changes.
          # Updates to these dependencies require manual review and testing to ensure compatibility and stability.
          - "@astrojs/*"
          - "astro"
          - "starlight-*"
        update-types:
          - "minor"

    # Labels for PRs
    # labels:
    #   - "dependencies"

    # Pull request branch naming
    pull-request-branch-name:
      separator: "-"

    # Commit message format (conventional commits)
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(devdeps)"
