name: Setup Nx
description: Configure Nx cache and affected detection

inputs:
  enable-cache:
    description: Enable Nx local cache
    required: false
    type: boolean
    default: false
  nx-cloud-token:
    description: Nx Cloud access token (empty string disables Nx Cloud)
    required: false
    type: string
    default: ''

runs:
  using: composite
  steps:
    # Set Nx Cloud access token for subsequent steps
    - name: Configure Nx Cloud
      shell: bash
      run: |
        echo "NX_CLOUD_ACCESS_TOKEN=${{ inputs.nx-cloud-token }}" >> $GITHUB_ENV
    # Cache Nx local cache between runs
    - name: Cache Nx
      if: inputs.enable-cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # ratchet:actions/cache@v4
      with:
        path: .nx/cache
        key: nx-${{ runner.os }}-${{ github.ref_name }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('**/project.json', 'nx.json') }}
        restore-keys: |
          nx-${{ runner.os }}-${{ github.ref_name }}-${{ hashFiles('pnpm-lock.yaml') }}-
          nx-${{ runner.os }}-${{ github.ref_name }}-
          nx-${{ runner.os }}-main-
          nx-${{ runner.os }}-

    # Sets NX_BASE and NX_HEAD for accurate affected detection
    - uses: nrwl/nx-set-shas@826660b82addbef3abff5fa871492ebad618c9e1 # ratchet:nrwl/nx-set-shas@v4
