packages:
  - packages/*
  - config
executionEnv:
  nodeVersion: 22.23.1
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  msw: true
  nx: true
  sharp: true
  unrs-resolver: true
  yarn: true
minimumReleaseAgeExclude:
  - generate-license-file@4.2.1
