import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "pathe";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { GleamManifestCommitted } from "../../src/policies/GleamManifestCommitted.js";
import { runHandler } from "../test-helpers.js";

describe("GleamManifestCommitted", () => {
	let testDir: string;

	beforeEach(() => {
		testDir = join(
			tmpdir(),
			`repopo-test-${Date.now()}-${Math.random().toString(36).slice(2)}`,
		);
		mkdirSync(testDir, { recursive: true });
	});

	afterEach(() => {
		rmSync(testDir, { recursive: true, force: true });
	});

	describe("policy matching", () => {
		it("should match gleam.toml", () => {
			expect(GleamManifestCommitted.match.test("gleam.toml")).toBe(true);
		});

		it("should match nested gleam.toml", () => {
			expect(GleamManifestCommitted.match.test("packages/app/gleam.toml")).toBe(
				true,
			);
		});

		it("should not match other files", () => {
			expect(GleamManifestCommitted.match.test("manifest.toml")).toBe(false);
			expect(GleamManifestCommitted.match.test("package.json")).toBe(false);
		});
	});

	describe("pass cases", () => {
		it("should pass when manifest.toml exists alongside gleam.toml", async () => {
			writeFileSync(
				join(testDir, "gleam.toml"),
				['name = "my_package"', 'version = "1.0.0"'].join("\n"),
			);
			writeFileSync(
				join(testDir, "manifest.toml"),
				"# This file was generated by Gleam\n",
			);

			const result = await runHandler(GleamManifestCommitted.handler, {
				file: "gleam.toml",
				root: testDir,
				resolve: false,
			});

			expect(result).toBe(true);
		});

		it("should pass when manifest.toml exists in a nested directory", async () => {
			const nestedDir = join(testDir, "packages", "app");
			mkdirSync(nestedDir, { recursive: true });
			writeFileSync(
				join(nestedDir, "gleam.toml"),
				['name = "my_app"', 'version = "1.0.0"'].join("\n"),
			);
			writeFileSync(
				join(nestedDir, "manifest.toml"),
				"# This file was generated by Gleam\n",
			);

			const result = await runHandler(GleamManifestCommitted.handler, {
				file: "packages/app/gleam.toml",
				root: testDir,
				resolve: false,
			});

			expect(result).toBe(true);
		});
	});

	describe("fail cases", () => {
		it("should fail when manifest.toml does not exist", async () => {
			writeFileSync(
				join(testDir, "gleam.toml"),
				['name = "my_package"', 'version = "1.0.0"'].join("\n"),
			);

			const result = await runHandler(GleamManifestCommitted.handler, {
				file: "gleam.toml",
				root: testDir,
				resolve: false,
			});

			expect(result).not.toBe(true);
			if (typeof result === "object" && "error" in result) {
				expect(result.error).toContain("Missing manifest.toml");
			}
		});

		it("should fail when manifest.toml is missing in nested directory", async () => {
			const nestedDir = join(testDir, "packages", "app");
			mkdirSync(nestedDir, { recursive: true });
			writeFileSync(
				join(nestedDir, "gleam.toml"),
				['name = "my_app"', 'version = "1.0.0"'].join("\n"),
			);

			const result = await runHandler(GleamManifestCommitted.handler, {
				file: "packages/app/gleam.toml",
				root: testDir,
				resolve: false,
			});

			expect(result).not.toBe(true);
			if (typeof result === "object" && "error" in result) {
				expect(result.error).toContain("Missing manifest.toml");
			}
		});
	});
});
