// Generated TypeScript definitions for CCL test data
// Do not edit manually - regenerated by sync-data.ts

export interface GeneratedTest {
  name: string;
  input: string;
  validation: string;
  expected: {
    count: number;
    entries?: Array<{ key: string; value: string }>;
    object?: any;
    value?: any;
    list?: any[];
    error?: boolean;
  };
  functions: string[];
  features: string[];
  behaviors: string[];
  variants: string[];
  source_test: string;
}

export interface TestCategory {
  name: string;
  description: string;
  tests: GeneratedTest[];
  file: string;
}

export interface TestStats {
  totalTests: number;
  totalAssertions: number;
  categories: Record<string, number>;
  functions: Record<string, number>;
  features: Record<string, number>;
  behaviors: Record<string, number>;
}

export interface SearchIndex {
  byName: Record<string, string[]>;
  byInput: Record<string, string[]>;
  byFunction: Record<string, string[]>;
  byFeature: Record<string, string[]>;
}

// Enum types for better type safety
export type CCLFunction = "parse" | "parse_value" | "filter" | "build_hierarchy" | "get_string" | "expand_dotted" | "get_list" | "get_int" | "get_float" | "get_bool" | "associativity" | "round_trip" | "canonical_format";
export type CCLFeature = "empty_keys" | "multiline" | "comments" | "whitespace" | "unicode" | "experimental_dotted_keys";
export type CCLBehavior = "tabs_preserve" | "list_coercion_enabled" | "list_coercion_disabled" | "boolean_strict" | "boolean_lenient" | "crlf_preserve_literal" | "crlf_normalize_to_lf" | "strict_spacing";

// Available functions for filtering
export const AVAILABLE_FUNCTIONS: CCLFunction[] = ["parse", "parse_value", "filter", "build_hierarchy", "get_string", "expand_dotted", "get_list", "get_int", "get_float", "get_bool", "associativity", "round_trip", "canonical_format"];

// Available features for filtering
export const AVAILABLE_FEATURES: CCLFeature[] = ["empty_keys", "multiline", "comments", "whitespace", "unicode", "experimental_dotted_keys"];

// Available behaviors for filtering
export const AVAILABLE_BEHAVIORS: CCLBehavior[] = ["tabs_preserve", "list_coercion_enabled", "list_coercion_disabled", "boolean_strict", "boolean_lenient", "crlf_preserve_literal", "crlf_normalize_to_lf", "strict_spacing"];
