// Generated TypeScript definitions for CCL test data
// Do not edit manually - regenerated by sync-data.ts

export interface GeneratedTest {
	name: string;
	input: string;
	validation: string;
	expected: {
		count: number;
		entries?: Array<{ key: string; value: string }>;
		object?: any;
		value?: any;
		list?: any[];
		error?: boolean;
	};
	functions: string[];
	features: string[];
	behaviors: string[];
	variants: string[];
	source_test: string;
}

export interface TestCategory {
	name: string;
	description: string;
	tests: GeneratedTest[];
	file: string;
}

export interface TestStats {
	totalTests: number;
	totalAssertions: number;
	categories: Record<string, number>;
	functions: Record<string, number>;
	features: Record<string, number>;
	behaviors: Record<string, number>;
}

export interface SearchIndex {
	byName: Record<string, string[]>;
	byInput: Record<string, string[]>;
	byFunction: Record<string, string[]>;
	byFeature: Record<string, string[]>;
}

// Enum types for better type safety
export type CCLFunction =
	| "parse"
	| "filter"
	| "build_hierarchy"
	| "parse_indented"
	| "get_string"
	| "get_list"
	| "canonical_format"
	| "get_int"
	| "get_float"
	| "get_bool"
	| "round_trip";
export type CCLFeature =
	| "empty_keys"
	| "comments"
	| "multiline"
	| "whitespace"
	| "unicode"
	| "optional_typed_accessors";
export type CCLBehavior =
	| "tabs_preserve"
	| "list_coercion_enabled"
	| "crlf_preserve_literal"
	| "crlf_normalize_to_lf"
	| "strict_spacing"
	| "list_coercion_disabled"
	| "boolean_strict"
	| "boolean_lenient";

// Available functions for filtering
export const AVAILABLE_FUNCTIONS: CCLFunction[] = [
	"parse",
	"filter",
	"build_hierarchy",
	"parse_indented",
	"get_string",
	"get_list",
	"canonical_format",
	"get_int",
	"get_float",
	"get_bool",
	"round_trip",
];

// Available features for filtering
export const AVAILABLE_FEATURES: CCLFeature[] = [
	"empty_keys",
	"comments",
	"multiline",
	"whitespace",
	"unicode",
	"optional_typed_accessors",
];

// Available behaviors for filtering
export const AVAILABLE_BEHAVIORS: CCLBehavior[] = [
	"tabs_preserve",
	"list_coercion_enabled",
	"crlf_preserve_literal",
	"crlf_normalize_to_lf",
	"strict_spacing",
	"list_coercion_disabled",
	"boolean_strict",
	"boolean_lenient",
];
