name: Renovate
on:
  schedule:
    # Run at 5 AM UTC on weekdays (matches "before 5am every weekday" in renovate.json5)
    - cron: '0 5 * * 1-5'
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # ratchet:actions/checkout@v4
      - uses: renovatebot/github-action@b11417b9eaac3145fe9a8544cee66503724e32b6 # ratchet:renovatebot/github-action@v43.0.8
        with:
          configurationFile: renovate.json5
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_FILTER: "tylerbutler/tools-monorepo"
          RENOVATE_ALLOWED_COMMANDS: '["^pnpm .*"]'
          RENOVATE_ALLOW_SCRIPTS: true
